[package]
name = "hello_macro"
version = "0.1.0"
edition = "2021"
description = "adds the method hello_macro that generates a greeting based on the name of the struct"
license = "MIT OR Apache-2.0"

[dependencies]
