[package]
name = "pancakes"
version = "0.1.0"
edition = "2021"

[dependencies]
hello_macro = { path = "../bogdan_hello_macro" }
hello_macro_derive = { path = "../bogdan_hello_macro/hello_macro_derive" }